# Ref. https://github.com/prometheus/prometheus/blob/master/documentation/examples/rbac-setup.yml
# Ref. https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gbookshelf-monitoring-prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gbookshelf-monitoring-prometheus
  namespace: gbookshelf-server
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gbookshelf-monitoring-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gbookshelf-monitoring-prometheus
subjects:
- kind: ServiceAccount
  name: gbookshelf-monitoring-prometheus
  namespace: gbookshelf-server
