global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    env: base # TODO: kustomize: patch it in each overlay

rule_files:
  - /etc/prometheus/rules/*.yaml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093 # NOTE: If alertmanager lives in different namespace, use FQDN ([my-svc].[my-namespace].svc.cluster.local:9093) instead

# Ref. https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml
scrape_configs:

- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'gbookshelf'
  static_configs:
  - targets: ['gbookshelf-server:2112']

- job_name: "kubernetes-apiservers"
  kubernetes_sd_configs:
    - role: endpoints
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    action: keep
    regex: default;kubernetes;https

- job_name: "kubernetes-nodes"
  kubernetes_sd_configs:
  - role: node
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: kubernetes.default.svc:443
  - source_labels: [__meta_kubernetes_node_name]
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/${1}/proxy/metrics

- job_name: 'kubernetes-cadvisor'
  kubernetes_sd_configs:
  - role: node
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: kubernetes.default.svc:443
  - source_labels: [__meta_kubernetes_node_name]
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

# - job_name: 'kubernetes-service-endpoints'
#   kubernetes_sd_configs:
#   - role: endpoints
#
#   relabel_configs:
#   - action: labelmap
#     regex: __meta_kubernetes_service_label_(.+)
#   - source_labels: [__meta_kubernetes_namespace]
#     action: replace
#     target_label: kubernetes_namespace
#   - source_labels: [__meta_kubernetes_service_name]
#     action: replace
#     target_label: kubernetes_name
#
# - job_name: 'kubernetes-services'
#   kubernetes_sd_configs:
#   - role: service
#
#   metrics_path: /probe
#   params:
#     module: [http_2xx]
#
#   relabel_configs:
#   - source_labels: [__address__]
#     target_label: __param_target
#   - target_label: __address__
#     replacement: blackbox-exporter.example.com:9115
#   - source_labels: [__param_target]
#     target_label: instance
#   - action: labelmap
#     regex: __meta_kubernetes_service_label_(.+)
#   - source_labels: [__meta_kubernetes_namespace]
#     target_label: kubernetes_namespace
#   - source_labels: [__meta_kubernetes_service_name]
#     target_label: kubernetes_name
#
# - job_name: 'kubernetes-ingresses'
#   kubernetes_sd_configs:
#   - role: ingress
#
#   metrics_path: /probe
#   params:
#     module: [http_2xx]
#
#   relabel_configs:
#   - source_labels: [__meta_kubernetes_ingress_scheme,__address__,__meta_kubernetes_ingress_path]
#     regex: (.+);(.+);(.+)
#     replacement: ${1}://${2}${3}
#     target_label: __param_target
#   - target_label: __address__
#     replacement: blackbox-exporter.example.com:9115
#   - source_labels: [__param_target]
#     target_label: instance
#   - action: labelmap
#     regex: __meta_kubernetes_ingress_label_(.+)
#   - source_labels: [__meta_kubernetes_namespace]
#     target_label: kubernetes_namespace
#   - source_labels: [__meta_kubernetes_ingress_name]
#     target_label: kubernetes_name
#
# - job_name: 'kubernetes-pods'
#   kubernetes_sd_configs:
#   - role: pod
#
#   relabel_configs:
#   - action: labelmap
#     regex: __meta_kubernetes_pod_label_(.+)
#   - source_labels: [__meta_kubernetes_namespace]
#     action: replace
#     target_label: kubernetes_namespace
#   - source_labels: [__meta_kubernetes_pod_name]
#     action: replace
#     target_label: kubernetes_pod_name
