apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gbookshelf
commonLabels:
  app: gbookshelf-server
resources:
- namespace.yaml
- gbookshelf-server/deployment.yaml
- gbookshelf-server/service.yaml
- prometheus/deployment.yaml
- prometheus/service.yaml
- prometheus/clusterRole.yaml
- alertmanager/deployment.yaml
- alertmanager/service.yaml
- grafana/deployment.yaml
- grafana/service.yaml
configMapGenerator:
- literals:
  - gbookshelf_bookshelf=mybookshelf
  - gbookshelf_server_port=2109
  - gbookshelf_metrics_port=2112
  - project_id=gbookshelf-dev
  - firestore_adminsdk_crential_file_path=/credentials/firebase/gbookshelf-firebase-adminsdk.json
  name: gbookshelf-server-config
- files:
  - gbookshelf-server/envoy.yaml
  name: gbookshelf-envoy-config
- literals:
  - tsdbRetention=24h
  name: prometheus-server-args
- literals:
  - dataRetention=24h
  name: alertmanager-args
- files:
  - prometheus/prometheus.yaml
  name: prometheus-server-config
- files:
  - prometheus/rules.yaml
  name: prometheus-rule-config
- files:
  - alertmanager/alertmanager.yaml
  name: alertmanager-config
- files:
  - grafana/provisioning/datasources/datasource.yaml
  name: grafana-datasource-config
- files:
  - grafana/provisioning/dashboards/dashboard.yaml
  - grafana/provisioning/dashboards/gbookshelf.json
  name: grafana-dashboard-config
secretGenerator:
- files:
  - .credentials/gbookshelf-firebase-adminsdk.json
  name: firebase-secret
  type: Opaque
