apiVersion: v1
kind: Service
metadata:
  name: gbookshelf-server
  labels:
    name: gbookshelf-server
spec:
  selector:
    name: gbookshelf-server
  # type: ClusterIP
  clusterIP: None # NOTE: Use headless service (load balancing by envoy instead of kube-proxy)
  ports:
  - name: http
    port: 8080 # envoy listeners port
    protocol: TCP
    targetPort: 8080
