---
# NOTE: internal Service using headless service (load balancing by envoy instead of kube-proxy)
apiVersion: v1
kind: Service
metadata:
  name: gbookshelf-server
  labels:
    name: gbookshelf-server
spec:
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: gbookshelf-server
  # type: ClusterIP
  clusterIP: None
---
# external Service with NodePort to temporarily expose a port to the Internet
apiVersion: v1
kind: Service
metadata:
  name: gbookshelf-gateway
  labels:
    name: gbookshelf-server
spec:
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    name: gbookshelf-server
  type: NodePort
---
# external Service with LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: gbookshelf-lb
  labels:
    name: gbookshelf-server
spec:
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: gbookshelf-server
  type: LoadBalancer
