apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: alertmanager
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: alertmanager
      annotations:
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        imagePullPolicy: Always
        args:
        - "--config.file=/etc/alertmanager/alertmanager.yaml"
        - "--storage.path=/alertmanager/"
        - "--data.retention=$(DATA_RETENTION)"
        # - "-web.external-url=WEB.EXTERNAL-URL"
        ports:
        - name: alertmanager
          containerPort: 9093
          protocol: TCP
        env:
        - name: DATA_RETENTION
          valueFrom:
            configMapKeyRef:
              name: alertmanager-args
              key: dataRetention
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager
          readOnly: true
        - name: alertmanager-storage-data-volume
          mountPath: /alertmanager
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
            defaultMode: 420
        - name: alertmanager-storage-data-volume
          emptyDir: {}
